use_frameworks!
target 'PVDBaseMVC_Tests' do
  pod 'PVDBaseMVC', :path => '../'
  
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'fourhands-client'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
